config/routes.rb
Rails.application.routes.draw do
  #set the index page
  resources :users
  root to: "pages#home"#:to => redirect('/welcome')
  # routes set for the following
  #get 'pages/home'
  #  match '/pages_home', to: "pages#home", via: get
  match '/login', to: 'sessions#new', via: :get
  match '/login_create', to: 'sessions#create', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete

  get 'pages/welcome'

  #  post "/adminfunctions/deleteUser
  post 'adminfunctions/makeAdmin'
  get 'adminfunctions/addUser'
  post 'adminfunctions/deleteUser'
  post 'adminfunctions/approveDriver'

  get 'profiles/index'
  post 'profiles/update'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'vanpools/index'
  get 'vanpools/new'
  post 'vanpools/create'
  post 'vanpools/join'
end

app/models/vanpool.rb
class Vanpool < ActiveRecord::Base
end

app/controllers/vanpools_controller.rb
class VanpoolsController < ApplicationController
  before_action :set_current_user

  def vanpool_params
    params.require(:vanpool).permit(:name, :cost, :max_capacity, :current_capacity, :start_time, :end_time, :pickup_location, :dropoff_location)
  end

  def index
    @vanpools = Vanpool.all
  end

  def new
  end

  def create
    v_name = vanpool_params[:name]
    v_cost = vanpool_params[:cost]
    v_max_capacity = vanpool_params[:max_capacity]
    v_start_time = vanpool_params[:start_time]
    v_end_time = vanpool_params[:end_time]
    v_pickup_location = vanpool_params[:pickup_location]
    v_dropoff_location = vanpool_params[:dropoff_location]
    v_current_capacity = 0

    flash[:notice] = "Vanpool #{v_name} successfully created"
    Vanpool.create!(name: v_name,
                    cost: v_cost,
                    current_capacity: v_current_capacity,
                    max_capacity: v_max_capacity,
                    start_time: v_start_time,
                    end_time: v_end_time,
                    pickup_location: v_pickup_location,
                    dropoff_location: v_dropoff_location)
    redirect_to vanpools_index_path
  end

  #TODO make rider and driver join seperately
  def join
    # If redirect_to_welcome is false, then redirect_to vanpools_index_path;
    # Otherwise, redirect_to pages_welcome_path, both with the output_msg inside flash[:notice]
    output_msg = " "
    redirect_to_welcome = false

    vanpool_ids = @current_user[:rider_vanpool_ids]
    if @current_user.nil?
      flash[:notice] = "user is nil"
      redirect_to pages_welcome_path and return
    end
    if vanpool_ids.nil?
      flash[:notice] = "47 vanpool_ids is nil", @current_user
      redirect_to pages_welcome_path and return
    end

    # Rider
    if !params[:vanpools].nil?
      params[:vanpools].keys.each do |vid|
        vid = vid.to_i
        added = false
        if vanpool_ids.nil?
          flash[:notice] = "57 vanpool_ids is nil"
          redirect_to pages_welcome_path and return
        end
        vanpool_ids.each do |id|
          if id == vid
            added = true
          end
        end
        if !added
          @current_user.rider_vanpool_ids_will_change!
          @current_user.rider_vanpool_ids << vid
          vanpool = Vanpool.find_by(id: vid)
          vanpool.current_capacity = vanpool.current_capacity + 1
          vanpool.save
          @current_user.save
        end
      end
      output_msg = output_msg + "#{@current_user.user_id}, you successfully joined the vanpool(s). "
      redirect_to_welcome = true
    elsif params[:vanpools].nil?
      output_msg = output_msg + "No vanpool selected to ride "
    end

    # Driver
    driver_vanpool_ids = @current_user[:driver_vanpool_ids]
    if !params[:vanpools_driver].nil?
      params[:vanpools_driver].keys.each do |vid|
        vid = vid.to_i
        added = false
        if driver_vanpool_ids.nil?
          flash[:notice] = "57 vanpool_ids is nil"
          redirect_to pages_welcome_path and return
        end
        vanpool = Vanpool.find_by(id: vid)
        driver_vanpool_ids.each do |id|
          if id == vid || !vanpool.driver.nil?
            added = true
          end
        end
        if !added
          @current_user.driver_vanpool_ids_will_change!
          @current_user.driver_vanpool_ids << vid
          vanpool.driver = @current_user.id
          vanpool.save
          @current_user.save
        end
      end

      output_msg = output_msg + "AND Volunteer to Drive Selected"
      redirect_to_welcome = true
    elsif params[:vanpools_driver].nil?
      output_msg = output_msg + "AND No vanpool selected to volunteer to drive"
    end

    flash[:notice] = output_msg
    if redirect_to_welcome
      redirect_to pages_welcome_path
    else
      redirect_to vanpools_index_path
    end
  end
end

app/views/vanpools/index.html.erb
<h1>All Vanpools:</h1>


<table class="table">
  <thead>
    <tr>
      <% if @current_user %>
        <th>Join Ride</th>
        <% if @current_user.approved %>
          <th>Volunteer to Drive</th>
        <% end %>
      <% end %>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <%= form_tag vanpools_join_path, :class => 'form' do %>
      <% @vanpools.each do |v| %>
        <tr>
          <% if @current_user %>
            <td>
              <%=check_box_tag "vanpools[#{v[:id]}]" %>
            </td>
            <% if @current_user.approved %>
              <td>
                <%=check_box_tag "vanpools_driver[#{v[:id]}]" %>
              </td>
            <% end %>
          <% end %>
          <td>
            <%= v.serializable_hash%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </br>
      <% if @current_user %>
        <%= submit_tag 'Join Vanpool', :class => 'btn btn-primary'%>
      <% end %>
    <% end %>

app/views/vanpools/new.html.erb
<%= form_tag vanpools_create_path, :class => 'form' do %>
  <%= label :vanpool, :name, 'Enter Name:', :class => 'col-form-label' %>
  <%= text_field :vanpool, 'name', :class => 'form-control'%>
  </br>
  <%= label :vanpool, :cost, 'Enter Cost:', :class => 'col-form-label' %>
  <%= text_field :vanpool, 'cost', :class => 'form-control'%>
  </br>
  <%= label :vanpool, :max_capacity, 'Enter Max Capacity:', :class => 'col-form-label' %>
  <%= text_field :vanpool, 'max_capacity', :class => 'form-control'%>
  </br>
  <%= label :vanpool, :start_time, 'Enter Start Time:', :class => 'col-form-label' %>
  <%= text_field :vanpool, 'start_time', :class => 'form-control'%>
  </br>
  <%= label :vanpool, :end_time, 'Enter End Time:', :class => 'col-form-label' %>
  <%= text_field :vanpool, 'end_time', :class => 'form-control'%>
  </br>
  <%= label :vanpool, :pickup_location, 'Enter Pickup Location:', :class => 'col-form-label' %>
  <%= text_field :vanpool, 'pickup_location', :class => 'form-control'%>
  </br>
  <%= label :vanpool, :dropoff_location, 'Enter Dropoff Location:', :class => 'col-form-label' %>
  <%= text_field :vanpool, 'dropoff_location', :class => 'form-control'%>
  </br>
  <%= submit_tag 'Create Vanpool', :class => 'btn btn-primary'%>
<% end %>