config/routes.rb
Rails.application.routes.draw do
  #set the index page
  resources :users
  root to: "pages#home"#:to => redirect('/welcome')
  # routes set for the following
  #get 'pages/home'
  #  match '/pages_home', to: "pages#home", via: get
  match '/login', to: 'sessions#new', via: :get
  match '/login_create', to: 'sessions#create', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete

  get 'pages/welcome'

  #  post "/adminfunctions/deleteUser
  post 'adminfunctions/makeAdmin'
  get 'adminfunctions/addUser'
  post 'adminfunctions/deleteUser'
  post 'adminfunctions/approveDriver'

  get 'profiles/index'
  post 'profiles/update'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'vanpools/index'
  get 'vanpools/new'
  post 'vanpools/create'
  post 'vanpools/join'
end

app/views/pages/home.html.erb
<%= button_to "List All Vanpools", vanpools_index_path, :method => :get%>
<h1>Vanpool Service System Home Page</h1>
<p>Welcome to the homepage of our amazing new web based Vanpool service system</p>
<p><strong>Create an account using the button on the top and let your journey begin</strong></p>

app/views/pages/welcome.html.erb
<% if @driver %>
  <h1>Welcome Driver!</h1>
  <% if !(@current_user.approved) %>
    <p style="background: red; color: white;"><strong><em>Pending Approval</em></strong></p>
  <% end %>
<% elsif @rider %>
  <h1>Welcome Rider!</h1>
<% end %>
<% if @admin %>
  <p> Admin Functions</p>
  <%= form_tag adminfunctions_makeAdmin_path, :class => 'form' do %>
    <%= label :user, :user_id, 'Enter User-ID:', :class => 'col-form-label' %>
    <%= text_field :user, 'user_id', :class => 'form-control'%>
    <%= submit_tag 'Make Admin', :class => 'btn btn-primary'%>
  <% end %>

  <%= form_tag adminfunctions_deleteUser_path, :class => 'form' do %>
    <%= label :user, :user_id, 'Enter User-ID:', :class => 'col-form-label' %>
    <%= text_field :user, 'user_id', :class => 'form-control'%>
    <%= submit_tag 'Remove user', :class => 'btn btn-primary'%>
  <% end %>
  </br>

  <% if !(@users.empty?) %>
    <h4 style="color:red;">Unapproved Drivers</h4>
    <table>
      <%= form_tag adminfunctions_approveDriver_path, :class => 'form' do %>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%=check_box_tag "unapproved_drivers[#{user[:id]}]" %>
            </td>
            <td>
              <%= user.serializable_hash %>
            </td>
          </tr>
        <% end %>
        </table>
        <%= submit_tag 'Approve Driver(s)', :class => 'btn btn-primary'%>
      <% end %>
  <% elsif @users.empty? %>
    <h4 style="color:green;"> All Drivers have been approved</h4>
  <% end %>


  </br></br>
  <%= button_to "Create New Vanpool", vanpools_new_path, :method => :get %>

<% else %>
  <p> User is not admin</p>
<% end %>
<%= button_to "List All Vanpools", vanpools_index_path, :method => :get%>