config/routes.rb
Rails.application.routes.draw do
  #set the index page
  resources :users
  root to: "pages#home"#:to => redirect('/welcome')
  # routes set for the following
  #get 'pages/home'
  #  match '/pages_home', to: "pages#home", via: get
  match '/login', to: 'sessions#new', via: :get
  match '/login_create', to: 'sessions#create', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete

  get 'pages/welcome'

  #  post "/adminfunctions/deleteUser
  post 'adminfunctions/makeAdmin'
  get 'adminfunctions/addUser'
  post 'adminfunctions/deleteUser'
  post 'adminfunctions/approveDriver'

  get 'profiles/index'
  post 'profiles/update'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'vanpools/index'
  get 'vanpools/new'
  post 'vanpools/create'
  post 'vanpools/join'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VanpoolServiceSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  </header>
  <div>
    <% if !(@current_user) %>
      <%= button_to('Sign up/Login', login_path, method: :get, :id => 'signupLogin') %>
      <%= button_to('Forgot Password', login_path, method: :get) %>
      <%= button_to('Home', root_path, method: :get) %>
    <% elsif @current_user %>
      <p>You are logged in as <%="#{@current_user.user_id}, with a vanpools_id: #{@current_user.rider_vanpool_ids}"%></p>
      <%= button_to('Logout', logout_path, method: :delete, :id => 'logout') %>
      <%= button_to("Home", pages_welcome_path, method: :get) %>
    <% end %>
  </div>
  <br/>

  <section>
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
  <%= yield %>
  </section>
  </body>
</html>